/*This class is generated by the XMLParser program.
Author: Petar Angelov (Petaaar). GitHub: https://github.com/Petaaar.
The project source code: https://github.com/Petaaar/XMLParser.
Thanks for using my parser!*/
namespace SASH.Custom
{
    using System;
    using System.IO;
    using System.Collections.Generic;


    public abstract class MyClass

    {
        private static string path;

        private int myNumber;

        private const string TAB;

        public static string publicField;

        public readonly int intField;

        public double sixAndAHalf;

        private virtual bool IsItTrue;

        public override string ToString;

        public void VoidMethod;

    }

}
